# Generated by Django 4.2.19 on 2025-02-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temp_field',
        ),
    ]
