# Generated by Django 4.2.19 on 2025-02-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_temp_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='secret_answer',
            new_name='pet_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secret_question',
        ),
    ]
